### PR TITLE
Auto yaw created and snap to yaw created and working

### PR DESCRIPTION
**Pull request by WhyDoesGodDoThis**
Created an auto yaw that needs to be calibrated.
Credit.

### CODE REVIEW

**Comment by WhyDoesGodDoThis** [comment]
Now working needs review

**Comment by mandrews281** [comment]
There are a couple of problems.  NavXSubsystem has a lot of code commented out.  Either we need or we don't.  I suspect we don't so delete it. 
Also I think the definition of DriveInput is nebulous at the moment.  Your atan2 is using it one way for X/Y and your DriveSubsystem is using it another.  Otherwise I think we can merge this.

**Comment by WhyDoesGodDoThis** [comment]
Don't merge need to read documentation.

**Comment by WhyDoesGodDoThis** [comment]
Some code reformatted
Errors fixed
Useless comments from example command removed

Still need to increase the tolerance on the auto  yaw filter.

**Pull request merged**
